{% set name = "eo-learn-features" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c6728627fa81735a0d27b9ae5f3bdf5316604fa99469d51b179339e509fec7b0

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - eo-learn-core >=1.0.0
    - numba >=0.53.0
    - numpy
    - python >=3.7
    - python-dateutil
    - scikit-image >=0.19.0
    - scikit-learn
    - scipy

test:
  imports:
    - eolearn
    - eolearn.core
    - eolearn.features

about:
  home: https://github.com/sentinel-hub/eo-learn
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A collection of feature manipulation utilities and EOTasks
  doc_url: https://eo-learn.readthedocs.io/en/latest/eolearn.features.html
  dev_url: https://github.com/sentinel-hub/eo-learn

extra:
  recipe-maintainers:
    - mxr-conda
