{% set name = "eo-learn-features" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 295616c09d8b6f816141ffdd6ddf29d841d408fe61a5a9b91028c6b5ce7672e8

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - eo-learn-core
    - numba >=0.43.1
    - numpy
    - python >=3.5
    - python-dateutil
    - scikit-image
    - scikit-learn
    - scipy

test:
  imports:
    - eolearn
    - eolearn.core
    - eolearn.features

about:
  home: https://github.com/sentinel-hub/eo-learn
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A collection of feature manipulation utilities and EOTasks
  doc_url: https://eo-learn.readthedocs.io/en/latest/eolearn.features.html
  dev_url: https://github.com/sentinel-hub/eo-learn

extra:
  recipe-maintainers:
    - mxr-conda
