{% set name = "eo-learn-features" %}
{% set version = "1.4.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ba3bcc409ee030489ce0749e15ffde0112091e1976f1ea23e7bc33b04156b587

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.5
  run:
    - eo-learn-core
    - numba >=0.43.1
    - numpy
    - python >=3.5
    - python-dateutil
    - scikit-image
    - scikit-learn
    - scipy

test:
  imports:
    - eolearn
    - eolearn.core
    - eolearn.features

about:
  home: https://github.com/sentinel-hub/eo-learn
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A collection of feature manipulation utilities and EOTasks
  doc_url: https://eo-learn.readthedocs.io/en/latest/eolearn.features.html
  dev_url: https://github.com/sentinel-hub/eo-learn

extra:
  recipe-maintainers:
    - zigaluksic
    - mxr-conda
